### ISSUE TITLE
A question regarding Instant-Dictionary.

### ISSUE THREAD

**Issue by VinylNix** [DoTheEvo/ANGRYsearch#1]
Greetings, DoTheEvo.

I'm sorry for posting an unrelated to this section question, but I've found no other way to contact you.
I have an issue regarding your other creation: Instant-Dictionary for Opera 12 (Opera Presto).
It's by far the best extension I've used in opera, but it has stopped working recently due to an unknown reason. Even an official link is no longer supporting it: https://addons.opera.com/en/extensions/details/instant-dictionary/
Although, it remains in the Google chrome archive: https://chrome.google.com/webstore/detail/instant-dictionary/fcjmbgoamdpbndikpbaoeoidaabejfmd?hl=en
So I have this extension installed right now and it was working perfectly yesterday, but not anymore. Any changes to the settings don't help at all. Is there anything I can do to make it work again? It's an essential part of my work in the browser and it's almost impossible to find an alternative.

And thank you for creating such an amazing tool.

**Comment by DoTheEvo** [comment]
huh, I was under the impression that the definition part of the extension stopped working ages ago. Thought that google changed API - the way how the extension communicates with their definition service.
Anyway I stopped developing and supporting it long ago as there was no real reason to do so since  opera moved on to be chrome-clone and chrome has google dictionary extension made by google employees themselves which also new opera can use as well.
https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?hl=en

Admirable you sticked to opera 12 for so long but you will encounter more and more issues with it.

**Comment by VinylNix** [comment]
I was forced to abandon that feature, but I still used it for the ability to translate from any language (even chinese/arabic) + possibility to play the selected fragments by a native speaker. It's a pity that you cannot make it working anymore, since a lot of people are still using opera 12 (there's even a still active forum dedicated to it). 
Well then, thanks for answering at least, I wasn't even sure that you were the one who created it.
Although you might consider upgrading it, since people can use it in a new Vivaldi browser (which is an opera presto continuation by the same developers) and will love it, because your extension combined translation, definition and audio in itself while keeping it neat and simple. Different variations of Google dictionary comprise of translation+audio or definition+audio only. Generally speaking I would always choose a simpler tool with more features than a more cumbersome analog that operates only in two languages.
