### ISSUE TITLE
Can't open text files from ANGRYsearch results

### ISSUE THREAD

**Issue by leninberg** [DoTheEvo/ANGRYsearch#15]
Hi!
Thanks for this wonderful app. I could install it without problems on my ubuntu 16.04 64bits system (mini.iso)
I have been testing and I can open mp3, jpg or pdf files from the results in ANGRYsearch (double click or right click -Open)
But it doesn't do anything when the file is text/plain.
Can you give me any advice on this?
Thanks in advance.

**Comment by DoTheEvo** [comment]
in terminal, this should show you what is your default application for that mime type
`xdg-mime query default text/plain`

this would set it to mousepad for example
`xdg-mime default mousepad.desktop text/plain`

once you done that you will see that a file - `mimeapps.list` appeared in `~/.config`
there you can more easily set up default applications if there are problems

if shit just dont work, then maybe run angrysearch from terminal and see if some errors appear in the terminal when you are trying to open txt files from angrysearch
another thing to try, assuming you just have default gedit and its not working, is to check if it works on its own, trying to from terminal opening some txt file `gedit whatever_file.txt` or if xdg works as it should `xdg-open whatever_file.txt` since that is the command that is used to open whatever mime type...  xdg is suppose to figure out what to open it with

**Comment by leninberg** [comment]
When I did
`xdg-mime query default text/plain`
I got gedit.desktop. It seems weird to me since I don't have gedit installed. Anyway,  I followed your instructions and wrote
`xdg-mime default leafpad.desktop text/plain`
And now it works when I open text files from ANGRYsearch (mimeapps.list was in .config too)

Thanks a lot for your prompt reply.
I forgot to say that I appreciated the concise explanations in the readme. Thumbs up to that!
