### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by Jaegrqualm** [DoTheEvo/ANGRYsearch#2]
When running from the terminal, I'm getting the following error

Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 19, in <module>
    import scandir
  File "/opt/angrysearch/scandir.py", line 577, in <module>
    scandir_helper = _scandir.scandir_helper
AttributeError: 'module' object has no attribute 'scandir_helper'

No change after reinstalling. I haven't actually run it since the last update, and I can't downgrade, because Arch. I tried messing around a tiny bit with scandir.py, trying to force an exception that looked like it might help, but to no avail.

**Comment by DoTheEvo** [comment]
There are 2 things you can try
* uninstall scandir from pip, `pip uninstall scandir` or maybe `sudo pip uninstall scandir`
* delete scandir.py from the /opt/angrysearch/

ultimately you can do also [this](http://i.imgur.com/XvwqBjT.gif)
instead of scandir it will use os.walk which in this version is the same speed as scandir I think
and in september with python 3.5 release os.walk will be scandir under the hood anyway

**Comment by Jaegrqualm** [comment]
Well, that was faster than I expected. Your first solution fixed it. Keeping a summer schedule has its benefits, it seems.
