### ISSUE TITLE
Huge resource drain

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#26]
Just now, something start using most of my (dual-core) CPU, and 8 GB of RAM and about 8 GB of swap. My suspect is AngrySearch, for (1) I'd just used it (by entering a very long search string, and then truncating it), (2) when I tried to log out, angrysearch.py was flagged as still running (though I couldn't see it in any task managers). The CPU situation persisted for five minutes, and the RAM and swap situation for longer - namely, until I restarted. (The log-out seemed to hang, so I had to reboot.)

Thanks.

Linux Mint 18 x64 Cinnamon.
AngrySearch 1.01

**Comment by DoTheEvo** [comment]
One time occurrence? No regex mode used?
If so hard to investigate such things...  

By long search string, do you mean single long continuous word, or many space separated words?
By truncating you mean deleting whole search, or some of the search terms in it by selecting them or ctrl+backspace?

Also it seems like you noticed the huge cpu and ram usage only later on exit, not as you did the search.
Could it be also the update of the database running and hanging up? Or only purely searching was done?

Did the search contain some special characters or just classic latin alphabet?

also no need to restart, open terminal and write `kilall angrysearch`

**Comment by ACinnamonUserInUK** [comment]
Dear 'Evo'

It was, thus far anyway, a one-time occurrence. I am having trouble
rediscovering the string in question. But I can tell you that it was
some 100 characters long, came from the Thunderbird debug console, and
contained both a bit of code and a file path. Probably the string
contained at least one space. I do not know about special characters. I
pasted the string into Angry and then (this is what I called the
'truncation') deleted all the characters that were not part of the
aforementioned filename. By this point, Angry may have started
searching, and perhaps the sought string contained characters that could
be construed as regex code.

I did indeed notice the resource spike only having finished with the
search. I don't know whether I'd closed the Angry window, but certainly
the spike persisted when (at whatever point this happened) that window
was shut. Could the problem owe to the database updating? Yes, perhaps.

I did try 'killall angry-search.py', which didn't work. I'll try to
remember 'killall angrysearch'.

I am sorry I can't give you more to go on. (I've removed the Thunderbird
AddOn that I was investigating, and I don't think there is a 'save
history' function in Angry.) If indeed AngrySearch was the cause of
this, because it was quite worrying. I started to wonder about whether
I'd some malware.

Yours

Nicholas

**Comment by DoTheEvo** [comment]
>it was some 100 characters long, came from the Thunderbird debug console, and contained both a bit of code and a file path.

yeah, something in there was not liked by angrysearch, usually it just crashed as I made it deal with plus sign, quotations, asterisk,...

if you be searching for some complicated strings, try switching to slow mode with that checkbox, it does not try to be fancy and special, if you search you write " or ( it actually searches for file containing those, as they are allowed characters in linux.
