### ISSUE TITLE
Could we have an option to change the panel icon to something, lighter, please?

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#27]
At present, on my not-so-good laptop monitor, the panel icon looks - until one squints at it - like an entirely black box, and so makes me thing that something's gone wrong (especially since, on Linux Mint Cinnamon at least, often things _do_ go wrong with panel icons). Thanks.

**Comment by DoTheEvo** [comment]
Ive seen such option in qbittorent,.. will think about it, but most likely no, icon looks like crap already, making the background color lightcolored... well it would just look worse

If you want you can edit the script and change the icon yourself.

* find icon you like, ideally simple svg but whatever will work, [I went here](https://www.iconfinder.com/search/?q=search&price=free&type=vector) and chose one of the magnifying glasses
* download the icon
* upload it to online [base64 convertor](https://www.base64-image.de/)
* click `copy image`  to copy the results in to the clipboard, and paste it in to some editor so you can remove the `data:image/svg+xml;base64,` part so that only raw giberish data are left, [here](http://pastebin.com/AcuGQ21J) is pastebin of the one I used in the example
* open angrysearch.py, search for `get_tray_icon` and you see there a loooong string of giberish in between tripple quotation marks, there you put the new string of giberish, that is your new picture encoded in base64
* save and see the results on the next run

[heres video of how to do it](https://i.frogbox.es/hm7)

**Comment by ACinnamonUserInUK** [comment]
Thank you for your tutorial. I have edited my gibberish (!) and all is well, although, oddly, the icon I chose was blue and the icon that's resulted is reddish-pink - but that's fine. Less good is that I'll have to perform the latter steps of the procedure after every (as I propose to call it) Angry update.
