### ISSUE TITLE
Feature request: allow exclusion of one directory with leafname X whilst allowing another with leafname X

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [DoTheEvo/ANGRYsearch#31]
I've got one user with a `Documents` folder in its home folder, and also another user with a `Documents` folder in _its_ home folder. I want AngrySearch to index one but not the other. Given that whole paths are not allowed in the exclusions field, this seems impossible.

**Comment by DoTheEvo** [comment]
that should work since [version 1.0.0 ](https://github.com/DoTheEvo/ANGRYsearch/releases/tag/v1.0.0)

>CHANGE: exclude directories by giving - full path or parent/target or target

so even just `<other username>/Documents` would work

though theres a bug in that version, that I forgot to tell the `angrysearch_update_database.py`  about this, and so it wont be ignored if you got it periodically automatically run on your system.

latest few commits fixed that, I guess I should push version 1.0.1 this weekedn, only if for this one fix and the new option to close the angrysearch window after opening file/folder

**Comment by ACinnamonUserInUK** [comment]
Thank you for the information. I am having trouble seeing what version of the program I have - perhaps because I installed it via git. Since I did install it that way, and since, possibly, the bug with the updater is causing a problem on my system (namely, occasionally disk thrashing occurs and I don't reach a usable desktop on login) I will git clone the latest version.
