### ISSUE TITLE
Feature: Allow use of the same database for many users of the same system.

### ISSUE THREAD

**Issue by map7** [DoTheEvo/ANGRYsearch#37]
We run thin clients at work and it would be great to use angrysearch here but it looks like currently each user would have to have their own database (which in our case is about 900MB big). A nice feature would be to have a centralised database so that we don't have to have a separate file per user.

**Comment by DoTheEvo** [comment]
will solve it in some way, at least I make sure that the variable of the database path will be only single line edit in the script if someone really wants it, instead of 3 lines as its now.
But might put it as an option in the preference file, thought I see some problems with that, that its not just trivial adding an option for a variable, some reorganization would be needed...

but whoever will be changing default database path needs to make sure that the place chosen will have write permission for all intended users, or they will need to run the script as root if they would want to update the database manually.
Alternatively I could be asking for sudo password during the update of the database as first versions of angrysearch had, but I am not fan of that.

at the moment if you wish you can search the script for `home + '/.cache/angrysearch/angry_database.db'`

and replace 3 occurrences of it with a string containing absolute path

[here is webm showing how](https://s1.webmshare.com/rNAPN.webm)

I am doing it in virtualbox manjaro, with sublime text, ctrl+D hotkey is doing multi cursor to edit all occurrences at the same time. Sudo is needed since no write permissions to /opt

**Comment by DoTheEvo** [comment]
in latest version you can edit the script and change`DATABASE_PATH` to where you want, only that single place.

You might also want to check out [fsearch](https://github.com/cboxdoerfer/fsearch)

https://github.com/DoTheEvo/ANGRYsearch/releases/tag/v1.0.1
